### GET /
GET http://localhost:5003

### Register a user POST /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "gilgamesh@gmail.com",
  "password": "123123123"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "gilgamesh@gmail.com",
  "password": "123123123"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMyNDE1MTk2LCJleHAiOjE3MzI1MDE1OTZ9.J-Qe0ZAA0nN03_ZzLvUv04PIDuY7AjVgzvgDjjim5HY

### Creates a new todo POST /TODOS (protected)
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMyNDE1MTk2LCJleHAiOjE3MzI1MDE1OTZ9.J-Qe0ZAA0nN03_ZzLvUv04PIDuY7AjVgzvgDjjim5HY
Content-Type: application/json

{
  "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5003/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMyNDE1MTk2LCJleHAiOjE3MzI1MDE1OTZ9.J-Qe0ZAA0nN03_ZzLvUv04PIDuY7AjVgzvgDjjim5HY
Content-Type: application/json

{
  "completed": 1
}

### Delete a todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMyNDE1MTk2LCJleHAiOjE3MzI1MDE1OTZ9.J-Qe0ZAA0nN03_ZzLvUv04PIDuY7AjVgzvgDjjim5HY
Content-Type: application/json
